<?php require_once __DIR__ . '/../../../backend/middleware/check_admin.php'; 
$pageTitle = 'Đánh Giá';
$extraCss = '<link rel="stylesheet" href="/PetsAccessories/admin/frontend/assets/css/categories.css">';
$extraJs = '<script src="/PetsAccessories/admin/frontend/assets/js/reviews.js"></script>';
require_once __DIR__ . '/../../layout/header.php';
?>

<div class="brands-container"><div id="messagesContainer"></div><h2>Danh sách bình luận</h2><div class="search-filter-section"><div class="search-filter-grid"><div class="form-group"><label>Tìm kiếm</label><input id="searchInput"></div><div class="form-group"><label>Trạng thái</label><select id="statusFilter"><option value="">Tất cả</option><option value="1">Hiện</option><option value="0">Ẩn</option></select></div></div><div class="search-filter-actions"><button class="btn btn-secondary" id="resetBtn">Làm mới</button><button class="btn btn-primary" id="filterBtn">Tìm kiếm</button></div></div><div class="table-wrapper"><table class="brands-table"><thead><tr><th>ID</th><th>Sản phẩm</th><th>Người dùng</th><th>Rating</th><th>Nội dung</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody id="reviewsTableBody"></tbody></table></div><h2 style="margin-top:30px;">Danh sách báo cáo</h2><div class="search-filter-section"><div class="search-filter-grid"><div class="form-group"><label>Trạng thái</label><select id="reportStatusFilter"><option value="">Tất cả</option><option value="0">Chờ xử lý</option><option value="1">Đã xử lý</option></select></div></div><div class="search-filter-actions"><button class="btn btn-secondary" id="resetReportsBtn">Làm mới</button><button class="btn btn-primary" id="filterReportsBtn">Tìm kiếm</button></div></div><div class="table-wrapper"><table class="brands-table"><thead><tr><th>ID</th><th>Sản phẩm</th><th>Người báo cáo</th><th>Lý do</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody id="reportsTableBody"></tbody></table></div></div>

<?php require_once __DIR__ . '/../../layout/footer.php'; ?>