<?php require_once __DIR__ . '/../../../backend/middleware/check_admin.php'; 
$pageTitle = 'Giao Hàng';
$extraCss = '<link rel="stylesheet" href="/PetsAccessories/admin/frontend/assets/css/categories.css">';
$extraJs = '<script src="/PetsAccessories/admin/frontend/assets/js/shipping.js"></script>';
require_once __DIR__ . '/../../layout/header.php';
?>

<div class="brands-container"><div id="messagesContainer"></div><div class="brands-header"><h2>🚚 Khu Vực Giao Hàng</h2><div class="brands-header-actions"><button class="btn btn-primary" id="addShippingBtn">➕ Thêm Khu Vực</button></div></div><div class="table-wrapper"><table class="brands-table"><thead><tr><th>ID</th><th>Khu vực</th><th>Phí ship</th><th>Dự kiến</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody id="shippingTableBody"></tbody></table></div></div><div id="shippingModal" class="modal"><div class="modal-content"><div class="modal-header"><h3 id="shippingModalTitle">➕ Thêm Khu Vực</h3><button class="close-btn" id="closeModalBtn">×</button></div><div class="modal-body"><form id="shippingForm"><div class="form-group-vertical"><label>Tên khu vực</label><input name="zone_name" required></div><div class="form-group-vertical"><label>Phí vận chuyển</label><input name="shipping_fee" type="number" min="0" required></div><div class="form-group-vertical"><label>Thời gian dự kiến</label><input name="estimated_delivery"></div><div class="form-group-vertical"><label>Trạng thái</label><select name="status"><option value="1">Kích hoạt</option><option value="0">Ẩn</option></select></div></form></div><div class="modal-footer"><button class="btn btn-secondary" id="cancelModalBtn">Hủy</button><button class="btn btn-primary" id="saveShippingBtn">💾 Lưu</button></div></div></div>

<?php require_once __DIR__ . '/../../layout/footer.php'; ?>